sudo: required # 관리자 권한갖기

language: generic # 언어(플랫폼)을 선택

services: # 도커환경 구성
  - docker

before_install: # 스크립트를 싱행할 수 있는 환경설정파일
  - echo "start Createing an image with dockerfile"
  - docker build -t wjsgmlwls79/docker-react-app -f Dockerfile.dev .

script: # 실행할 스크립트 (테스트 실행)
  - docker run -e CI=true wjsgmlwls79/docker-react-app npm run test -- --coverage

after_success: # 테스트 성공 후 할일
  - echo "Test Success"